# Generated by Django 5.0.6 on 2024-06-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('tipo', models.CharField()),
                ('ix', models.SmallIntegerField()),
                ('temp', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
            options={
                'db_table': 'registros',
                'managed': False,
            },
        ),
    ]
