# Generated by Django 5.0.6 on 2024-06-25 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camaras',
            fields=[
                ('ix', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='Canal')),
                ('name', models.CharField(default='LIBRE', max_length=15, verbose_name='Nombre')),
                ('desc', models.TextField(default='', max_length=100, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Umbrales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Límite inferior')),
                ('high', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Límite superior')),
                ('ix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Camaras_ix', to='frio.camaras')),
            ],
        ),
    ]
