# Generated by Django 5.0.6 on 2024-07-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frio', '0003_alter_camaras_options_alter_umbrales_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camaras',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Mostrar'),
        ),
    ]
